BEGIN;

ALTER TABLE IF EXISTS "django_migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "django_content_type" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "auth_permission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "auth_group" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "auth_group_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "auth_user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "auth_user_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "auth_user_user_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "django_admin_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "django_session" ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS "inventory_asset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "inventory_employee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "inventory_assignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "inventory_maintenancelog" ENABLE ROW LEVEL SECURITY;

COMMIT;
