BEGIN;

CREATE TABLE IF NOT EXISTS "inventory_asset" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "type" varchar(20) NOT NULL,
    "serial_number" varchar(100) NOT NULL UNIQUE,
    "status" varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS "inventory_employee" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "department" varchar(255) NOT NULL,
    "email" varchar(254) NOT NULL
);

CREATE TABLE IF NOT EXISTS "inventory_assignment" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "date_assigned" date NOT NULL,
    "date_returned" date NULL,
    "asset_id" bigint NOT NULL,
    "employee_id" bigint NOT NULL,
    CONSTRAINT "inventory_assignment_asset_id_fk"
        FOREIGN KEY ("asset_id")
        REFERENCES "inventory_asset" ("id")
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "inventory_assignment_employee_id_fk"
        FOREIGN KEY ("employee_id")
        REFERENCES "inventory_employee" ("id")
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS "inventory_maintenancelog" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "issue_description" text NOT NULL,
    "technician" varchar(255) NOT NULL,
    "date" date NOT NULL,
    "resolved" boolean NOT NULL,
    "asset_id" bigint NOT NULL,
    CONSTRAINT "inventory_maintenancelog_asset_id_fk"
        FOREIGN KEY ("asset_id")
        REFERENCES "inventory_asset" ("id")
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS "inventory_assignment_asset_id_idx"
    ON "inventory_assignment" ("asset_id");

CREATE INDEX IF NOT EXISTS "inventory_assignment_employee_id_idx"
    ON "inventory_assignment" ("employee_id");

CREATE INDEX IF NOT EXISTS "inventory_maintenancelog_asset_id_idx"
    ON "inventory_maintenancelog" ("asset_id");

COMMIT;
