"""Thin barrel re-exporting all inventory view modules."""

from .views_api import (
    AssetAPIDetailView,
    AssetAPIListView,
    AssetAssignAPIView,
    AssetBulkDeleteAPIView,
    AssetReturnAPIView,
    EmployeeAPIDetailView,
    EmployeeAPIListView,
)
from .views_assets import (
    AssetAddRedirectView,
    AssetDeleteView,
    AssetDetailView,
    AssetListView,
    AssetUpdateView,
    AssignAssetView,
    ReturnAssetView,
)
from .views_auth import (
    AuthLoginView,
    AuthLogoutView,
    ForgotPasswordEmailView,
    ForgotPasswordSetView,
    ForgotPasswordVerifyView,
)
from .views_background import (
    BackgroundJobCreateView,
    BackgroundJobDetailView,
    BackgroundJobDownloadView,
)
from .views_dashboard import DashboardView
from .views_employee import (
    EmployeeAssetDetailView,
    EmployeeAssetsView,
    EmployeeConfirmAssetView,
    EmployeeDashboardView,
    EmployeeMaintenanceRequestView,
    EmployeeMarkAllNotificationsReadView,
    EmployeeMarkNotificationReadView,
    EmployeePasswordChangeView,
    EmployeeReportIssueView,
    EmployeeReturnRequestView,
    EmployeeSettingsView,
)
from .views_errors import (
    error_bad_request,
    error_not_found,
    error_permission_denied,
    error_server_error,
)
from .views_extras import (
    NotificationAPIView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    ProfileAvatarUploadView,
    ProfileView,
    ReportsView,
    SettingsView,
)
from .views_import_export import (
    ExportAssetCSVView,
    ImportAssetCSVExecuteView,
    ImportAssetCSVValidateView,
)
from .views_maintenance import (
    CompleteMaintenanceView,
    MaintenanceLogCreateView,
    MaintenanceLogDeleteView,
    MaintenanceLogUpdateView,
)
from .views_staff_employees import (
    EmployeeAddRedirectView,
    EmployeeDeleteView,
    EmployeeDetailView,
    EmployeeListView,
    EmployeeUpdateView,
)

__all__ = [
    "AssetAPIDetailView",
    "AssetAPIListView",
    "AssetAssignAPIView",
    "AssetAddRedirectView",
    "AssetBulkDeleteAPIView",
    "AssetDeleteView",
    "AssetDetailView",
    "AssetListView",
    "AssetReturnAPIView",
    "AssetUpdateView",
    "AssignAssetView",
    "AuthLoginView",
    "AuthLogoutView",
    "BackgroundJobCreateView",
    "BackgroundJobDetailView",
    "BackgroundJobDownloadView",
    "CompleteMaintenanceView",
    "DashboardView",
    "EmployeeAddRedirectView",
    "EmployeeAPIDetailView",
    "EmployeeAPIListView",
    "EmployeeAssetDetailView",
    "EmployeeAssetsView",
    "EmployeeConfirmAssetView",
    "EmployeeDashboardView",
    "EmployeeDeleteView",
    "EmployeeDetailView",
    "EmployeeListView",
    "EmployeeMaintenanceRequestView",
    "EmployeeMarkAllNotificationsReadView",
    "EmployeeMarkNotificationReadView",
    "EmployeePasswordChangeView",
    "EmployeeReportIssueView",
    "EmployeeReturnRequestView",
    "EmployeeSettingsView",
    "EmployeeUpdateView",
    "ExportAssetCSVView",
    "ForgotPasswordEmailView",
    "ForgotPasswordSetView",
    "ForgotPasswordVerifyView",
    "ImportAssetCSVExecuteView",
    "ImportAssetCSVValidateView",
    "MaintenanceLogCreateView",
    "MaintenanceLogDeleteView",
    "MaintenanceLogUpdateView",
    "NotificationAPIView",
    "NotificationListView",
    "NotificationMarkAllReadView",
    "NotificationMarkReadView",
    "ProfileAvatarUploadView",
    "ProfileView",
    "ReportsView",
    "ReturnAssetView",
    "SettingsView",
    "error_bad_request",
    "error_not_found",
    "error_permission_denied",
    "error_server_error",
]
