# Generated by Django 5.1.3 on 2026-06-25 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_asset_asset_status_idx_asset_asset_type_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
