# Generated by Django 5.1.3 on 2026-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_asset_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Technical & Core Programme Directorates', 'Technical & Core Programme Directorates'), ('Capacity Building & Innovation Directorates', 'Capacity Building & Innovation Directorates'), ('Institutional Support & Advisory Operations', 'Institutional Support & Advisory Operations')], max_length=255),
        ),
    ]
